=== livioso/dbC/exercise I/Employees.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="employees">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="employee" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element name="token">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="kell" />
										<xs:enumeration value="mino" />
										<xs:enumeration value="desa" />
										<xs:enumeration value="stuj" />
										<xs:enumeration value="rubn" />
										<xs:enumeration value="brck" />
										<xs:enumeration value="kyka" />
										<xs:enumeration value="coli" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
              <xs:element type="xs:string" name="email"/>
              <xs:element type="xs:anyURI" name="website"/>
            </xs:sequence>
            <xs:attribute type="xs:anyURI" name="profilepicture"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== livioso/dbC/exercise I/subtask I/Employees.xml
<?xml version="1.0" encoding="utf-8"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Employees.xsd">
	<employee profilepicture="http://goo.gl/p4Cwkw">
		<name>Stefan Ujamaa</name>
		<token>stuj</token>
		<email>stefan@ujamaa.tv</email>
		<website>google.com</website>
	</employee>
	<employee profilepicture="http://goo.gl/XEYZm1">
		<name>Ruben Bnall</name>
		<token>rubn</token>
		<email>ruben@bnall.sh</email>
		<website>google.com</website>
	</employee>
	<employee profilepicture="http://goo.gl/Kk2lF1">
		<name>Corinna Liscona</name>
		<token>coli</token>
		<email>corinna@liscona.be</email>
		<website>google.com</website>
	</employee>
</employees>
